CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username VARCHAR(16) NOT NULL,
    password CHAR(60) NOT NULL,
    key VARCHAR(675) NOT NULL
);

CREATE TABLE passwords(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    data VARCHAR(945)
);